---@alias null vim.NIL

---@alias NvimReddit.Thing
---| NvimReddit.Listing
---| NvimReddit.Comment
---| NvimReddit.Link
---| NvimReddit.More

---@alias NvimReddit.Votable
---| NvimReddit.Comment
---| NvimReddit.Link

---@alias NvimReddit.Selectable
---| NvimReddit.Comment
---| NvimReddit.Link
---| NvimReddit.More

---@class (exact) NvimReddit.Listing
---@field data NvimReddit.ListingData
---@field kind "Listing"
---@field show_subreddit boolean|nil

---@class (exact) NvimReddit.Comment
---@field data NvimReddit.CommentData
---@field kind "t1"
---@field padding integer|nil
---@field media NvimReddit.Image|nil
---@field open boolean|nil
---@field player_job vim.SystemObj|nil
---@field mark integer|nil

---@class (exact) NvimReddit.Link
---@field data NvimReddit.LinkData
---@field kind "t3"
---@field show_subreddit boolean|nil
---@field parsed NvimReddit.Block[]|nil
---@field expando_mark integer|nil
---@field open boolean|nil
---@field domain_url string|nil
---@field gallery_selected integer|nil
---@field player_job vim.SystemObj|nil
---@field mark integer|nil

---@class (exact) NvimReddit.Subreddit
---@field data NvimReddit.SubredditData
---@field kind "t5"

---@class (exact) NvimReddit.ListingData
---@field before string | null
---@field children (NvimReddit.Thing)[]
---@field dist integer | null
---@field after string | null

---@class (exact) NvimReddit.LinkData
---@field locked boolean
---@field saved boolean
---@field send_replies boolean
---@field contest_mode boolean
---@field crosspost_parent? string
---@field name string
---@field mod_reason_by null
---@field thumbnail_width integer | null
---@field author_flair_text string | null
---@field subreddit string
---@field media NvimReddit.MediaData | null
---@field permalink string
---@field author_premium boolean
---@field media_embed NvimReddit.MediaEmbed
---@field subreddit_type string
---@field removed_by null
---@field is_video boolean
---@field subreddit_name_prefixed string
---@field archived boolean
---@field author_patreon_flair boolean
---@field link_flair_richtext any[]
---@field is_original_content boolean
---@field is_gallery? boolean
---@field awarders any[]
---@field can_mod_post boolean
---@field treatment_tags any[]
---@field banned_by null
---@field mod_note null
---@field link_flair_text_color NvimReddit.FlairTextColor | null
---@field mod_reports any[]
---@field allow_live_comments boolean
---@field subreddit_subscribers number
---@field selftext string
---@field thumbnail string
---@field discussion_type null
---@field gallery_data? NvimReddit.GalleryData
---@field likes boolean | null
---@field edited false | number
---@field over_18 boolean
---@field upvote_ratio number
---@field is_meta boolean
---@field top_awarded_type null
---@field quarantine boolean
---@field hide_score boolean
---@field author_flair_richtext any[]
---@field score number
---@field content_categories null
---@field category null
---@field suggested_sort string
---@field visited boolean
---@field all_awardings unknown[]
---@field secure_media_embed NvimReddit.MediaEmbed
---@field approved_by null
---@field num_comments number
---@field approved_at_utc null
---@field gilded number
---@field mod_reason_title null
---@field num_reports null
---@field no_follow boolean
---@field link_flair_css_class string
---@field can_gild boolean
---@field url string
---@field title string
---@field author_fullname string
---@field clicked boolean
---@field link_flair_type NvimReddit.FlairType
---@field pwls number
---@field domain string
---@field is_crosspostable boolean
---@field author_is_blocked boolean
---@field url_overridden_by_dest? string
---@field secure_media NvimReddit.MediaData | null
---@field removed_by_category null
---@field banned_at_utc null
---@field author_cakeday? true
---@field spoiler boolean
---@field subreddit_id string
---@field created number
---@field media_metadata? table<string, NvimReddit.Media>
---@field link_flair_template_id string
---@field media_only boolean
---@field hidden boolean
---@field removal_reason "legal" | null
---@field selftext_html string | null
---@field report_reasons null
---@field author_flair_template_id string | null
---@field created_utc number
---@field ups number
---@field is_reddit_media_domain boolean
---@field author string
---@field author_flair_text_color NvimReddit.FlairTextColor | null
---@field stickied boolean
---@field author_flair_type NvimReddit.FlairType
---@field link_flair_text string | null
---@field num_crossposts number
---@field gildings NvimReddit.Gildings
---@field user_reports any[]
---@field distinguished NvimReddit.Distinguished
---@field author_flair_css_class null
---@field is_created_from_ads_ui boolean
---@field id string
---@field is_robot_indexable boolean
---@field link_flair_background_color string
---@field wls number
---@field downs number
---@field thumbnail_height integer | null
---@field is_self boolean
---@field pinned boolean
---@field total_awards_received number
---@field author_flair_background_color string | null
---@field view_count null
---@field preview? NvimReddit.Preview
---@field post_hint? string

---@alias NvimReddit.Distinguished null | "moderator" | "admin" | "special" -- https://redd.it/19ak1b

---@alias (exact) NvimReddit.FlairTextColor
---| "dark"
---| "light"

---@alias (exact) NvimReddit.FlairType
---| "text"

---@class (exact) NvimReddit.GalleryData
---@field items NvimReddit.GalleryItem[]

---@class (exact) NvimReddit.GalleryItem
---@field id integer
---@field media_id string
---@field caption string | nil

---@class (exact) NvimReddit.Gildings
-- unknown

---@class (exact) NvimReddit.MediaData
---@field reddit_video NvimReddit.RedditVideo | nil
---@field oembed NvimReddit.Oembed | nil
---@field type string | nil

---@class (exact) NvimReddit.Oembed
---@field html string
---@field height number
---@field version string
---@field author_name string
---@field provider_name string
---@field thumbnail_height number
---@field author_url string
---@field type string
---@field thumbnail_width number
---@field width number
---@field thumbnail_url string
---@field title string
---@field provider_url string

---@class (exact) NvimReddit.RedditVideo
---@field fallback_url string
---@field has_audio boolean
---@field is_gif boolean
---@field transcoding_status string
---@field scrubber_media_url string
---@field dash_url string
---@field duration number
---@field width number
---@field hls_url string
---@field bitrate_kbps number
---@field height number

---@class (exact) NvimReddit.MediaEmbed
---@field content string | nil
---@field width number | nil
---@field height number | nil
---@field scrolling boolean | nil
---@field media_domain_url string | nil

---@class (exact) NvimReddit.Media
---@field status string
---@field e string
---@field m string
---@field ext? string
---@field p table[]
---@field s NvimReddit.MediaSource
---@field t? string
---@field id string

---@class (exact) NvimReddit.MediaSource
---@field y integer
---@field x integer
---@field u? string
---@field gif? string
---@field mp4? string

---@class (exact) NvimReddit.Preview
---@field images NvimReddit.PreviewImage[]
---@field enabled boolean

---@class (exact) NvimReddit.PreviewImage
---@field id string
---@field source NvimReddit.PreviewImageSource
---@field variants NvimReddit.Gildings
---@field resolutions NvimReddit.PreviewImageSource[]

---@class (exact) NvimReddit.PreviewImageSource
---@field url string
---@field width number
---@field height number

---@class (exact) NvimReddit.CommentData
---@field locked boolean
---@field saved boolean
---@field send_replies boolean
---@field associated_award unknown
---@field collapsed_reason_code unknown
---@field name string
---@field mod_reason_by unknown
---@field controversiality number
---@field author_flair_text string | null
---@field subreddit string
---@field link_author? string
---@field permalink string
---@field author_premium boolean
---@field subreddit_type string
---@field depth number
---@field unrepliable_reason unknown
---@field comment_type unknown
---@field link_title? string
---@field is_submitter boolean
---@field awarders unknown[]
---@field can_mod_post boolean
---@field banned_by unknown
---@field collapsed boolean
---@field mod_note unknown
---@field link_url? string
---@field mod_reports unknown[]
---@field collapsed_because_crowd_control unknown
---@field likes boolean | null
---@field edited false | number
---@field approved_by unknown
---@field body_html string
---@field score number
---@field all_awardings unknown[]
---@field top_awarded_type unknown
---@field score_hidden boolean
---@field approved_at_utc unknown
---@field gilded number
---@field mod_reason_title unknown
---@field author_patreon_flair boolean
---@field num_reports unknown
---@field no_follow boolean
---@field can_gild boolean
---@field collapsed_reason unknown
---@field author_flair_richtext unknown[]
---@field author_fullname? string
---@field author string
---@field author_is_blocked boolean
---@field banned_at_utc unknown
---@field body string
---@field treatment_tags unknown[]
---@field created number
---@field subreddit_name_prefixed string
---@field subreddit_id string
---@field removal_reason "legal" | null
---@field replies NvimReddit.Listing | ""
---@field report_reasons unknown
---@field author_flair_template_id? string
---@field created_utc number
---@field ups number
---@field id string
---@field author_flair_text_color? string
---@field stickied boolean
---@field author_flair_type string
---@field archived boolean
---@field gildings NvimReddit.Gildings
---@field user_reports unknown[]
---@field distinguished NvimReddit.Distinguished
---@field author_flair_css_class unknown
---@field link_id string
---@field downs number
---@field parent_id string
---@field total_awards_received number
---@field author_flair_background_color string | null
---@field media_metadata? table<string, NvimReddit.Media>

---@class (exact) NvimReddit.SubredditData
---@field accept_followers boolean
---@field banner_img string
---@field banner_size number[] | null
---@field community_icon string
---@field description string
---@field display_name_prefixed string
---@field display_name string
---@field free_form_reports boolean
---@field header_size number[] | null
---@field icon_img string
---@field icon_size any
---@field key_color string
---@field link_flair_enabled boolean
---@field name string
---@field public_description string
---@field restrict_commenting boolean
---@field restrict_posting boolean
---@field show_media boolean
---@field submit_text_label string
---@field subscribers number
---@field title string
---@field url string
---@field user_is_contributor boolean
---@field user_is_moderator boolean
---@field user_is_muted boolean
---@field user_is_subscriber boolean
---
---HACK: Everything after this point is an extention of the base class
---which is above. Maybe I will make this correct and make sense in the future
---
---@field accounts_active_is_fuzzed boolean
---@field accounts_active number
---@field active_user_count number
---@field advertiser_category string
---@field all_original_content boolean
---@field allow_discovery boolean
---@field allow_galleries boolean
---@field allow_images boolean
---@field allow_polls boolean
---@field allow_predictions_tournament boolean
---@field allow_predictions boolean
---@field allow_videogifs boolean
---@field allow_videos boolean
---@field banner_background_color string
---@field banner_background_image string
---@field can_assign_link_flair boolean
---@field can_assign_user_flair boolean
---@field collapse_deleted_comments boolean
---@field comment_score_hide_mins number
---@field community_reviewed boolean
---@field created_utc number
---@field created number
---@field description_html string | null
---@field disable_contributor_requests boolean
---@field emojis_custom_size any
---@field emojis_enabled boolean
---@field has_menu_widget boolean
---@field header_img string
---@field header_title string
---@field hide_ads boolean
---@field id string
---@field is_crosspostable_subreddit boolean | null
---@field is_enrolled_in_new_modmail any
---@field lang string
---@field link_flair_position string
---@field mobile_banner_image string
---@field notification_level string | null
---@field original_content_tag_enabled boolean
---@field over18 boolean
---@field prediction_leaderboard_entry_type string
---@field primary_color string
---@field public_description_html string
---@field public_traffic boolean
---@field quarantine boolean
---@field show_media_preview boolean
---@field spoilers_enabled boolean
---@field submission_type string
---@field submit_link_label string
---@field submit_text_html string
---@field submit_text string
---@field subreddit_type string
---@field suggested_comment_sort string | null
---@field user_can_flair_in_sr boolean | null
---@field user_flair_background_color any
---@field user_flair_css_class any
---@field user_flair_enabled_in_sr boolean
---@field user_flair_position string
---@field user_flair_richtext any[]
---@field user_flair_template_id any
---@field user_flair_text_color any
---@field user_flair_text any
---@field user_flair_type string
---@field user_has_favorited boolean
---@field user_is_banned boolean
---@field user_sr_flair_enabled boolean
---@field user_sr_theme_enabled boolean
---@field videostream_links_count? number
---@field whitelist_status string
---@field wiki_enabled boolean
---@field wls number

---@class (exact) NvimReddit.More
---@field data NvimReddit.MoreData
---@field kind "more"
---@field padding integer|nil
---@field link_id string|nil
---@field self_index integer|nil
---@field parent NvimReddit.Comment|NvimReddit.Listing|nil

---@class (exact) NvimReddit.MoreData
---@field children string[]
---@field count integer
---@field depth integer
---@field id string
---@field name string
---@field parent_id string
